#  setting base image
FROM python:3.8-slim

# cd into app
WORKDIR /app

# cp contents into app
COPY . /app

# install packages inside the requirements file added safety to download from py server
RUN pip install --trusted-host pypi.python.org -r requirements.txt 

# use port 80
EXPOSE 80

# Run it
CMD ["python", "main.py"]