# creating the sa in the kube-system ns - as our role is created in that namespace check main tf 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations: 
    eks.amazon.com/role-arn: arn:aws:iam::341880147273:role/eks-cluster-autoscaler  # the arn of the eks autoscaler role
---
# create rbac policies for autoscaler 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources: ["events", "endpoints"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods", "eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods", "status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods", "eviction"]
    verbs: ["create"]
  