#bind the service account with the role
apiVersion: v1
kind: ServiceAccount 
metadata: 
  name: aws-test
  namespace: default
  eks.amazonaws.com/role-arn: arn:aws:iam::341880147273:role/test-oidc #associate our role with this sa