
# exposing my-python-api-server to internet
apiVersion: v1
kind: Service
metadata:
  name: public-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # by default k8s creates a lb in public subnets hene dont need to give furher configurations
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 80
      targetPort: web